/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimize */
        post: operations["optimize_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtest */
        post: operations["backtest_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frontier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frontier */
        get: operations["frontier_frontier_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestRequest */
        BacktestRequest: {
            /** Universe */
            universe: string[];
            /** Method */
            method: string;
            constraints?: components["schemas"]["Constraints"];
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /** Rebalance */
            rebalance?: string | null;
            /** Lookback Years */
            lookback_years?: number | null;
            /** Transaction Cost Bps */
            transaction_cost_bps?: number | null;
            /** Benchmarks */
            benchmarks?: string[] | null;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Tickers */
            tickers: string[];
            /** Dates */
            dates: string[];
            /** Strategies */
            strategies: {
                [key: string]: components["schemas"]["StrategyResult"];
            };
            /** Significance */
            significance: {
                [key: string]: unknown;
            };
            provenance: components["schemas"]["Provenance"];
        };
        /**
         * Constraints
         * @description Allocation constraints for ``/optimize`` and every optimizer.
         *
         *     Defaults encode the canonical long-only, fully-invested portfolio.
         */
        Constraints: {
            /**
             * Long Only
             * @default true
             */
            long_only: boolean;
            /**
             * Fully Invested
             * @default true
             */
            fully_invested: boolean;
            /** Max Weight */
            max_weight?: number | null;
            /** Min Weight */
            min_weight?: number | null;
            /** Leverage Cap */
            leverage_cap?: number | null;
        };
        /**
         * ErrorResponse
         * @description Typed error contract. ``error`` is a stable machine code; ``detail`` is human-readable.
         */
        ErrorResponse: {
            /** Error */
            error: string;
            /** Detail */
            detail: string;
        };
        /** FrontierPointModel */
        FrontierPointModel: {
            /** Ret */
            ret: number;
            /** Vol */
            vol: number;
            /** Sharpe */
            sharpe: number;
        };
        /**
         * FrontierPortfolio
         * @description A named portfolio on/under the frontier (tangency or min-variance).
         */
        FrontierPortfolio: {
            /** Method */
            method: string;
            /** Tickers */
            tickers: string[];
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Exp Return */
            exp_return: number;
            /** Exp Vol */
            exp_vol: number;
            /** Sharpe */
            sharpe: number;
            /** Risk Contrib */
            risk_contrib: {
                [key: string]: number;
            };
        };
        /** FrontierResponse */
        FrontierResponse: {
            /** Tickers */
            tickers: string[];
            /** Frontier Points */
            frontier_points: components["schemas"]["FrontierPointModel"][];
            tangency: components["schemas"]["FrontierPortfolio"];
            min_var: components["schemas"]["FrontierPortfolio"];
            random_cloud: components["schemas"]["RandomCloud"];
            provenance: components["schemas"]["Provenance"];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Engine Hash */
            engine_hash: string;
            /** Universe */
            universe: string[];
        };
        /** OptimizeRequest */
        OptimizeRequest: {
            /** Universe */
            universe: string[];
            /** Method */
            method: string;
            constraints?: components["schemas"]["Constraints"];
            /** As Of */
            as_of?: string | null;
            /** Mu Method */
            mu_method?: string | null;
            /** Cov Method */
            cov_method?: string | null;
            /** Risk Free */
            risk_free?: number | null;
        };
        /** OptimizeResponse */
        OptimizeResponse: {
            /** Method */
            method: string;
            /** Tickers */
            tickers: string[];
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Exp Return */
            exp_return: number;
            /** Exp Vol */
            exp_vol: number;
            /** Sharpe */
            sharpe: number;
            /** Risk Contrib */
            risk_contrib: {
                [key: string]: number;
            };
            /** As Of */
            as_of?: string | null;
            provenance: components["schemas"]["Provenance"];
        };
        /**
         * Provenance
         * @description Where a result came from — the honesty/reproducibility envelope.
         *
         *     Carried on every successful response so the web can show *exactly* which
         *     data window, risk-free rate, and engine revision produced the numbers, and
         *     assert that the result is out-of-sample.
         */
        Provenance: {
            /** Engine Hash */
            engine_hash: string;
            /** Risk Free */
            risk_free: number;
            /** Data Start */
            data_start: string | null;
            /** Data End */
            data_end: string | null;
            /** As Of */
            as_of?: string | null;
            /**
             * Oos Only
             * @default true
             */
            oos_only: boolean;
            /** Generated Utc */
            generated_utc: string;
        };
        /** RandomCloud */
        RandomCloud: {
            /** Vol */
            vol: number[];
            /** Ret */
            ret: number[];
        };
        /** StrategyResult */
        StrategyResult: {
            /** Name */
            name: string;
            metrics: components["schemas"]["TearsheetModel"];
            /** Equity Curve */
            equity_curve: number[];
            /** Drawdown */
            drawdown: number[];
            /** Rolling Sharpe */
            rolling_sharpe: number[];
            /** Weights Over Time */
            weights_over_time: number[][];
            /** Rebalance Dates */
            rebalance_dates: string[];
            /** Turnover */
            turnover: number[];
        };
        /**
         * TearsheetModel
         * @description JSON-native mirror of :class:`argmin.analytics.metrics.Tearsheet`, plus
         *     PSR/DSR and a bootstrap Sharpe CI so the web has every headline metric in one
         *     object.
         */
        TearsheetModel: {
            /** Total Return */
            total_return: number;
            /** Cagr */
            cagr: number;
            /** Ann Return */
            ann_return: number;
            /** Ann Vol */
            ann_vol: number;
            /** Sharpe */
            sharpe: number;
            /** Sortino */
            sortino: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Calmar */
            calmar: number;
            /** Var 95 */
            var_95: number;
            /** Cvar 95 */
            cvar_95: number;
            /** Hit Rate */
            hit_rate: number;
            /** Best Day */
            best_day: number;
            /** Worst Day */
            worst_day: number;
            /** Avg Turnover */
            avg_turnover?: number | null;
            /** Psr */
            psr?: number | null;
            /** Dsr */
            dsr?: number | null;
            /** Sharpe Ci Low */
            sharpe_ci_low?: number | null;
            /** Sharpe Ci High */
            sharpe_ci_high?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    optimize_optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizeResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    backtest_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    frontier_frontier_get: {
        parameters: {
            query: {
                universe: string;
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrontierResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
